#!/usr/bin/env node
/**
 * Regenerate the local sample media used to try the CLI out.
 *
 * `samples/` is gitignored: it is ~14MB of binaries, which does not belong in
 * git history or the npm tarball. Run this to recreate it.
 *
 *   node scripts/make-samples.mjs
 *
 * Photos come from Lorem Picsum (Unsplash-licensed, free to use). Videos are
 * generated by ffmpeg's synthetic sources, so they are copyright-free by
 * construction and the shapes are ours to choose.
 */
import { mkdir, writeFile, rm } from "node:fs/promises";
import { spawn } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const imagesDir = join(root, "samples", "images");
const videosDir = join(root, "samples", "videos");

/** name, width, height — varied aspect ratios and file sizes. */
const PHOTOS = [
  ["landscape-wide", 1920, 1080],
  ["portrait-tall", 1080, 1920],
  ["square-large", 1600, 1600],
  ["panorama", 2400, 800],
  ["thumbnail-small", 400, 300],
  ["hero-huge", 3000, 2000],
  ["banner-thin", 1800, 400],
  ["photo-medium", 1200, 900],
];

/** name, WxH, fps, seconds, lavfi source, container. */
const CLIPS = [
  ["clip-1080p-30fps", "1920x1080", 30, 4, "testsrc2", "mp4"],
  ["clip-720p-60fps", "1280x720", 60, 3, "testsrc2", "mp4"],
  ["clip-vertical", "1080x1920", 30, 3, "testsrc2", "mp4"],
  ["clip-480p-24fps", "854x480", 24, 3, "smptebars", "mov"],
  ["clip-small-240p", "320x240", 15, 2, "testsrc2", "mp4"],
];

function run(bin, args) {
  return new Promise((resolve, reject) => {
    const child = spawn(bin, args, { stdio: ["ignore", "ignore", "pipe"] });
    let err = "";
    child.stderr.on("data", (c) => (err += c.toString()));
    child.on("error", reject);
    child.on("close", (code) =>
      code === 0 ? resolve() : reject(new Error(err.trim() || `exit ${code}`)),
    );
  });
}

async function main() {
  await rm(join(root, "samples"), { recursive: true, force: true });
  await mkdir(imagesDir, { recursive: true });
  await mkdir(videosDir, { recursive: true });

  console.log("Downloading photos…");
  await Promise.all(
    PHOTOS.map(async ([name, w, h]) => {
      const res = await fetch(`https://picsum.photos/seed/${name}/${w}/${h}`);
      if (!res.ok) throw new Error(`${name}: HTTP ${res.status}`);
      await writeFile(
        join(imagesDir, `${name}.jpg`),
        Buffer.from(await res.arrayBuffer()),
      );
      console.log(`  ${name}.jpg (${w}x${h})`);
    }),
  );

  // A few non-JPEG sources so a run exercises more than one decoder.
  const { default: sharp } = await import("sharp");
  const seed = join(imagesDir, "photo-medium.jpg");
  await sharp(seed).png().toFile(join(imagesDir, "graphic-flat.png"));
  await sharp(seed)
    .resize(800)
    .webp({ quality: 90 })
    .toFile(join(imagesDir, "already-webp.webp"));
  await sharp(seed).resize(600).tiff().toFile(join(imagesDir, "scan.tiff"));
  console.log("  graphic-flat.png, already-webp.webp, scan.tiff");

  console.log("\nGenerating videos with ffmpeg…");
  for (const [name, size, fps, seconds, source, ext] of CLIPS) {
    // mandelbrot and a few other sources reject `duration`; -t bounds them all.
    await run("ffmpeg", [
      "-hide_banner",
      "-loglevel",
      "error",
      "-y",
      "-f",
      "lavfi",
      "-i",
      `${source}=size=${size}:rate=${fps}`,
      "-f",
      "lavfi",
      "-i",
      "sine=frequency=440",
      "-t",
      String(seconds),
      "-c:v",
      "libx264",
      "-pix_fmt",
      "yuv420p",
      "-crf",
      "18",
      "-preset",
      "veryfast",
      "-c:a",
      "aac",
      "-shortest",
      join(videosDir, `${name}.${ext}`),
    ]);
    console.log(`  ${name}.${ext} (${size} @ ${fps}fps)`);
  }

  console.log("\nDone. Try it:\n  node dist/cli.js samples --dry-run");
}

main().catch((err) => {
  console.error(`\nFailed: ${err.message}`);
  if (String(err.message).includes("ENOENT")) {
    console.error("ffmpeg is required for the video samples.");
  }
  process.exit(1);
});
